# Site settings
title: Kenneth Test
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is Kenneth Sutton's test of jekyll using github and netlify.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kenneth-test.netlify.com" # the base hostname & protocol for your site

github_username:  homefries

# Build settings
markdown: kramdown
